name: iOS checks

on:
  pull_request:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: swift-actions/setup-swift@v2

      # Getting the last actual version from "master" branch
      - name: Get latest version from master
        run: |
          git fetch origin master
          latest_version=$(git show origin/master:PersonaClick.podspec | awk -F"'" '/s.version *=/ {print $2}')
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      # Installing dependencies
      - name: Install
        run: swift package resolve

      - name: Debug current branch
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Files in current directory:"
          ls -R

      # Checking podspec using latest version
      - name: Lint
        if: ${{ !cancelled() }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
          LATEST_VERSION: ${{ env.LATEST_VERSION }}
        run: pod spec lint --allow-warnings
