name: iOS checks

on:
  pull_request:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - name: Install
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --parallel

      - name: Lint
        if: always()
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod spec lint --allow-warnings
