name: iOS checks

on:
  pull_request:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - name: Install
        run: swift package resolve

      - name: Lint
        if: ${{ !cancelled() }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
        run: pod spec lint --allow-warnings
