name: iOS publish Swift package and Cocoapods

on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current branch
        id: current_branch
        run: |
          if [ -z "${{ github.head_ref }}" ]; then
            echo "Current branch: ${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          else
            echo "Current branch: ${{ github.head_ref }}" >> $GITHUB_ENV
          fi

      - name: Version
        env:
          FILE_PATH: 'PersonaClick.podspec'
        id: version
        run: |
          current_version=$(awk -F"'" '/s.version *=/ {print $2}' "$FILE_PATH")
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
        run: gh release create "$VERSION" --title=$VERSION --generate-notes

      - name: Publish to cocoapods.org
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
        run: pod trunk push --allow-warnings
