name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  find-release-commit:
    uses: personaClick/workflow/.github/workflows/reusable-release-commit-finder.yaml@master
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  bump-version:
    needs: find-release-commit
    if: |
      github.event_name == 'workflow_dispatch' || (
        github.event_name == 'push' &&
        needs.find-release-commit.outputs.hasCommit == 'false')
    uses: personaClick/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    permissions: write-all
    secrets:
      appSecret: ${{ secrets.VERSIONER_SECRET }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}
    with:
      appId: ${{ vars.VERSIONER_ID }}
      reviewerUsername: iwwwanow
